name: Build and Release

on:
  push:
    tags:
      - 'v*'   # 只有以 v 开头的 tag 才会触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up PowerShell
        uses: potatoqualitee/psmodulecache@v6

      - name: Run build script
        shell: pwsh
        run: scripts/build.ps1

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/evs_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
